[metadata]
name = "ssh-hosts"
description = "A channel to select hosts from your SSH config"
requirements = ["rg"]

[source]
command = "rg '^Host(name)? ' $HOME/.ssh/config --no-filename --no-line-number | tr -s ' ' | cut -d' ' -f2- | tr ' ' '\n' | rg -v '^$'"

[preview]
command = "rg -A 8 -m 1 '^Host {0}( |$)' $HOME/.ssh/config"

[keybindings]
enter = "actions:connect"

[actions.connect]
description = "SSH into the selected host"
command = "ssh -tt '{}'"
mode = "execute"
