#!/usr/bin/env bash
# =========================================================
# install-devcontainer.sh — devenv-based devcontainer bootstrap
#
# Scaffolds a devenv dev environment + Dev Container into a
# project so `devpod up` (or VS Code Dev Containers) gives you
# all the tools from nixconf. Uses the official devenv base
# image; the container builds the toolset from devenv.nix.
#
# Usage:  ./scripts/install-devcontainer.sh [options] [PROJECT_DIR]
# =========================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/examples/dev-env"

PROJECT_DIR="."
FORCE=0
ASSUME_YES=0

usage() {
  cat <<EOF
Usage: install-devcontainer.sh [options] [PROJECT_DIR]

Bootstraps a devenv-based devcontainer into PROJECT_DIR (default: .):

  1. Copies the nixconf devenv template (examples/dev-env) in.
  2. Validates it with 'devenv test' (builds the env, generates
     .devcontainer/devcontainer.json from devenv.nix).
  3. Prints devpod / VS Code Dev Containers next steps.

Requires: nix + devenv on PATH (see scripts/install-linux.sh).

Options:
  -f, --force      Overwrite existing devenv.nix / devcontainer.json
  -y, --yes        Assume yes to all prompts
  -h, --help       Show this help message

Exit codes: 0=success 1=error 2=usage 3=dependencies
EOF
}

log() { printf '==> %s\n' "$*" >&2; }
warn() { printf '!!  %s\n' "$*" >&2; }
err() { printf '[ERROR] %s\n' "$*" >&2; }

confirm() {
  local prompt="$1"
  if [ "$ASSUME_YES" = "1" ]; then
    return 0
  fi
  local reply
  printf '%s [y/N] ' "$prompt" >&2
  read -r reply
  case "$reply" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -f|--force) FORCE=1 ;;
    -y|--yes)   ASSUME_YES=1 ;;
    -h|--help)  usage; exit 0 ;;
    -*)         err "Unknown option: $1"; usage >&2; exit 2 ;;
    *)          PROJECT_DIR="$1" ;;
  esac
  shift
done

check_deps() {
  command -v nix >/dev/null 2>&1 || {
    err "Nix is required. Install it first:"
    err "  $REPO_ROOT/scripts/install-linux.sh"
    exit 3
  }
  command -v devenv >/dev/null 2>&1 || {
    err "devenv is required. Install it, e.g.:"
    err "  nix profile install nixpkgs#devenv"
    err "(or run scripts/install-linux.sh, which ships devenv in .#tools)"
    exit 3
  }
}

copy_template() {
  local dest
  mkdir -p "$PROJECT_DIR/.devcontainer"

  if [ -e "$PROJECT_DIR/devenv.nix" ] && [ "$FORCE" != "1" ]; then
    warn "devenv.nix already exists; leaving it in place (use -f to overwrite)."
  else
    if [ -e "$PROJECT_DIR/devenv.nix" ] && ! confirm "Overwrite $PROJECT_DIR/devenv.nix?"; then
      warn "Skipping devenv.nix."
    else
      cp "$TEMPLATE_DIR/devenv.nix" "$PROJECT_DIR/devenv.nix"
      log "Copied devenv.nix -> $PROJECT_DIR/devenv.nix"
    fi
  fi

  dest="$PROJECT_DIR/.devcontainer/devcontainer.json"
  if [ -e "$dest" ] && [ "$FORCE" != "1" ]; then
    warn "$dest already exists; leaving it in place (use -f to overwrite)."
  else
    if [ -e "$dest" ] && ! confirm "Overwrite $dest?"; then
      warn "Skipping devcontainer.json."
    else
      cp "$TEMPLATE_DIR/.devcontainer/devcontainer.json" "$dest"
      log "Copied devcontainer.json -> $dest"
    fi
  fi
}

validate() {
  log "Running 'devenv test' in $PROJECT_DIR..."
  # shellcheck disable=SC2016
  (cd "$PROJECT_DIR" && devenv test)
}

main() {
  check_deps

  if [ ! -d "$TEMPLATE_DIR" ]; then
    err "Template not found at $TEMPLATE_DIR — is this the nixconf repo?"
    exit 1
  fi

  copy_template
  validate

  cat <<EOF

Devcontainer ready in $PROJECT_DIR.

What was set up:
  - devenv.nix                tools + LSPs (edit packages/languages per repo)
  - .devcontainer/devcontainer.json  devenv base image (generated by devenv)

Use it with devpod:
  cd "$PROJECT_DIR"
  devpod up .                 # or the 'du' alias
  devpod ssh .                # or 'ds'

Or with VS Code Dev Containers:
  code .  ->  Reopen in Container

Tooling inside the container comes from devenv.nix. To change tools, edit
devenv.nix and re-run: devenv test && devpod up .
EOF
}

main "$@"